/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c16b7a0ec920c9c7104bf0f25f57a479)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	CODELOUD_INTEREST_HOSTNAMES: "localhost,127.0.0.1" | "codeloud.xyz";
	TURNSTILE_SECRET: string;
	CODELOUD_INTEREST_DB?: D1Database;
	TURNSTILE_SITE_KEY?: "0x4AAAAAAESQJEws32hnSB2M";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface LocalEnv {
		ASSETS: Fetcher;
		CODELOUD_INTEREST_HOSTNAMES: "localhost,127.0.0.1";
		TURNSTILE_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CODELOUD_INTEREST_HOSTNAMES" | "TURNSTILE_SECRET" | "TURNSTILE_SITE_KEY">> {}
}
